### ISSUE TITLE
Permission Denied on Creating RocksDB database

### ISSUE THREAD

**Issue by funkfreakout** [valeriansaliou/sonic#165]
I am getting these results when inserting an index into the `kv` store. 

```
(DEBUG) - opening key-value database for collection: <a31f4960>
(DEBUG) - configuring key-value database
(ERROR) - failed opening kv: Failed to create RocksDB directory: `Os { code: 13, kind: PermissionDenied, message: "Permission denied" }`.

```
I guess it is because the readwritedirectory for `kv` and `fst` stores is `/var/lib/sonic/store/*` . Is there a way to give write permissions on root folders to sonic?

**Comment by valeriansaliou** [comment]
This is an UNIX permissions issue. Check that the user + group you run Sonic with has folder creation + RW permissions on that folder.

**Comment by alexgorbatchev** [comment]
Had the same issue with example `docker-compose.yaml`, need to add `user: root`.

```yaml
version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    user: root    // <-------------------------- ADD THIS
    command: start --user root --pass root file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./data:/data:rw
```
