### ISSUE TITLE
Data loss when running in Docker

### ISSUE THREAD

**Issue by BenSlabbert** [valeriansaliou/sonic#185]
I am running sonic with the following docker-compose config

```
version: '3.7'

services:
  sonic:
    image: valeriansaliou/sonic:v1.2.3
    ports:
      - 1491:1491
    volumes:
      - sonic-data:/var/lib/sonic/store/
      - ./sonic/sonic.cfg:/etc/sonic.cfg

volumes:
  sonic-data:
    driver: local
```

When I run my app I ingest data into Sonic and the QUERY/SUGGEST commands work as expected. However, if I stop and restart this container `docker-compose down; docker-compose up` and run the same QUERY/SUGGEST requests I get empty responses.

Is the data previously ingested not re-indexed? Or is my docker volume configuration incorrect?

I am using the config file here: https://github.com/valeriansaliou/sonic/blob/master/config.cfg

**Comment by valeriansaliou** [comment]
Hello there! Do you see any database file being created in your Docker volume? Are they still there when you shutdown your Docker instance?

Also, do you see the Sonic shutdown event in the logs when you stop your Docker container? (Sonic should perform final syncs and FST consolidations when you SIGTERM it)

**Comment by BenSlabbert** [comment]
After inspecting the docker volume it is empty, I then had a poke around the running container and found that in the dir `/usr/src/sonic` there is a `data` dir with the `kv` and `fst` directories specified in the config file as 

```
path = "./data/store/kv/"
```
and
```
path = "./data/store/fst/"
```
respectively.

I updated my compose file as follows:

```
version: '3.7'

services:
  sonic:
    image: valeriansaliou/sonic:v1.2.3
    ports:
      - 1491:1491
    volumes:
      - sonic-data:/usr/src/sonic
      - ./sonic/sonic.cfg:/etc/sonic.cfg

volumes:
  sonic-data:
    driver: local
```

and now it is working as expected, thank you @valeriansaliou
